command:
- "python"
- "app.py"

env:
- name: "SPACE_ID"
  value: "01f04cfe4c8e1e83a9950c58631eb42f"
- name: "DB_HOST"
  value: "instance-f9da02db-1194-45e2-a3f3-d3072141b145.database.azuredatabricks.net"
- name: "DB_PORT"
  value: "5432"
- name: "DB_NAME"
  value: "zuzanak"
- name: "DB_USER"
  value: "zuzana.kovacsova@databricks.com"